# Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
  name: ordering-service
spec:
  ports:
    - protocol: "TCP"
      port: 8080    # Port inside the cluster
      targetPort: 8080   # Port exposed to the outside
  selector:
    app: ordering-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-service
spec:
  selector:
    matchLabels:
      app: ordering-service
  replicas: 2
  template:
    metadata:
      labels:
        app: ordering-service
    spec:
      containers:
        - name: ordering-service
          image: ordering-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:   # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address
              value: h2
            - name: DB_NAME  # Setting Database name
              value: h2db
            - name: DB_USERNAME  # Setting Database username
              value: root
            - name: DB_PASSWORD # Setting Database password
              value: root
# This seperator --- below is MANDATORY!!!
---